# Generated by Django 4.0.6 on 2022-08-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.DateField(default='2002-05-03'),
            preserve_default=False,
        ),
    ]
